version: '4'

networks:
  database:
    driver: bridge
  minio:
    driver: bridge

services:
  app:
    build: ./nuxt
    volumes:
      - ./nuxt/:/nuxt:delegated
      - nuxt-node_modules:/nuxt/node_modules
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      - MINIO_ENDPOINT=minio
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    ports:
      - '3000:3000'
      - '24678:24678'
    command: bash -c "npx prisma migrate dev && npx prisma db push && npm run dev"
    depends_on:
      - db
      - minio
    networks:
      - database
      - minio

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - database

  minio:
    image: minio/minio:RELEASE.2023-12-20T01-00-02Z
    ports:
      - "9000:9000"
      - "9001:9001"
    command: minio server /export --address :9000 --console-address :9001
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio:/export
    networks:
      - minio

volumes:
  nuxt-node_modules:
  postgres-data:
